version: '2'
services:

  backend:
    image: $IMAGE_DEV
    container_name: $CONTAINER_NAME
    volumes:
      - ./../application/:/application
    mem_limit: 500m
    environment:
      DATABASE: "mysql+pymysql://root:1234@mysql:3306/flash_test"
      DATABASE_LOG: "TRUE"
      EVENT_URL: "localhost"
      RUN_MIGRATE: "FALSE"
    ports:
      - 8080:80

  mysql:
    image: mysql:5.7
    container_name: $CONTAINER_DB_NAME
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: flash_test
    ports:
      - 3306:3306
    command: ['--sql-mode=NO_BACKSLASH_ESCAPES','--character-set-server=utf8', '--collation-server=utf8_spanish2_ci']
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
