#%RAML 1.0

title: Api
version: v1
mediaType: application/json
baseUri: https://miweb.com/v1

types:
  api_response_ok:
      properties: 
        error: boolean
        code: number
        message: string
        data: string
      example:
        error: false
        code: 2000
        message: SUCCESS
        data: ok
/api:
    post:
      description: demo.
      body:
        application/json:
          properties:
            id: string
            name: string
      responses:
        200:
          body:
            application/json:
              type: api_response_ok


