#%RAML 1.0

title: Gamma
version: v1
mediaType: application/json
baseUri: https://gamma-qa.lacafetalab.com/v1

types: 
  
  student_point:
    properties: 
      error: boolean
      code: number
      message: string
      data: student_pto
  student_pto:
    properties: 
      total: integer
      level_max: integer
      level_min: integer
      level: integer
    
  student_api:
    properties: 
      error: boolean
      code: number
      message: string
      data: student
  student:
    properties: 
      name: string
      last_name: string
      image: string
      campus: string
      
  challenges:
    properties: 
      error: boolean
      code: number
      message: string
      data: challenge[]
  challenge:
    properties: 
      id: string
      title: string
      description: string
      points: integer
      project: string
      current_date: string
      progress_total: integer
      finish_at: string
  progresses:
    properties: 
      error: boolean
      code: number
      message: string
      data: progress[]
  progress:
    properties: 
      id: string
      total: integer
      progress: integer
      seen: boolean | string
      status: string
      challenge_id: string
  api_response_ok:
      properties: 
        error: boolean
        code: number
        message: string
        data: string
      example:
        error: false
        code: 2000
        message: SUCCESS
        data: ok
  api_response_id:
      properties: 
        error: boolean
        code: number
        message: string
        data:
          properties: 
            id: string
      example:
        error: false
        code: 2000
        message: SUCCESS
        data: 
          id: "bb9697a5-ea0f-4116-b03a-d71efc5ec459"
  reward_list:
    properties: 
      id: string
      point: integer
      stock: integer
      expiration: string
      title: string
      image: string
      description: string
      requirement: string
      condition: string
      map: string
      current_date: string
  claim_list:
    properties: 
      id: string
      code: string
      reward_id: string
      status: string
      expired: integer
  reward_create:
    properties: 
      point: integer
      stock: integer
      expiration:
        type: string
        required: false
      title: string
      image: string
      description: string
      requirement: string
      condition: string
      map: string
  claim_create:
    properties: 
      code: string
      reward_id: string
    example:
      code: "IRFa-VaY2b"
      reward_id: "930f3218-2096-4170-8a62-31631d06e7fe"
  claim_it:
    properties: 
      code: string
    example:
      code: "IRFa-VaY2b"
/gamma:
  /challenge:
    get:
      description: Retorna la lista de retos
      responses:
        200:
          body:
            application/json:              
              type: challenges
              example: !include examples/challenges.json
  /progress:
    get:
      description: Retorna la lista de progresos de los retos
      responses:
        200:
          body:
            application/json:              
              type: progresses
              example: !include examples/progress.json
    patch:
      description: actauliza algun parametro de un progreso
      body: 
        application/json:
          properties:
            id: array
            seen: boolean
      responses: 
        200:
          body:
            application/json:
              type: api_response_ok
              
  /student:
    get:
      description: Retorna la descripcion de un alumno
      responses:
        200:
          body:
            application/json:              
              type: student_api
              example: !include examples/student.json
    /points:
      get:
        description: Retorna los puntos acumulados y el nivel en el que se encuentra
        responses: 
          200:
            body: 
              application/xml:
                type: student_point
                example: !include examples/points.json
              

  /reward:
    get:
      description: lista todos los premios
      responses:
        200:
          body:
            application/json:
              properties: 
                error: boolean
                code: number
                message: string
                data: reward_list[]
              example: !include examples/reward_list.json
    post:
      description: crear un uno premio, la imagen se sube con la api "v1/storages/gamma/form"
      body: 
        application/json:
          type: reward_create
          example: !include examples/reward_create.json
      responses: 
        200:
          body: 
            application/json:
              type: api_response_id

  /claim:
    post:
      description: para guardar el codigo de canje, la api valida si el premio esta caducado, si el alumno tiene los puntos para canjearlo.
      queryParameters: 
        student_id:
          type: string
      body: 
        application/json:
          type: claim_create
      responses: 
        200:
          body: 
            application/json:
              type: api_response_ok
    get:
      description: lista todos los premios canjeados
      queryParameters: 
        student_id:
          type: string
      responses:
        200:
          body:
            application/json:
              properties: 
                error: boolean
                code: number
                message: string
                data: claim_list[]
              example: !include examples/claim_list.json
    /it:
      post:
        description: servicio para canjear el premio con el codigo
        queryParameters: 
          student_id:
            type: string
        body: 
          application/json:
            type: claim_it
        responses: 
          200:
            body: 
              application/json:
                type: api_response_ok


  /auth:
    /token:
      post:
        description: genera el token a travez del codigo de estudiante y/o el id de loguin
        body: 
          application/json:
            properties: 
              code: string
              id:
                required: false
                type: string
            example:
              code: U16347735
        responses: 
          200:
            body: 
              application/json:
                properties: 
                  error: boolean
                  code: number
                  message: string
                  data: string
                example: !include examples/auth_token.json
    /login:
      post:
        description: loguea a un usario en gamma, con el token que se genero en unservicio anterior
        body: 
          application/json:
            properties: 
              token: string
            example:
              token: eyJ0eXAiIjp7ImNvZGUiOiJVMTc0OTM0IiwiaWQiOm51bGx9LCJleHAiOjE1NjYHB9Xhf7YwAWyHD2qeORA_6s4eLbqL9ut4
        responses: 
          200:
            body: 
              application/json:
                properties: 
                  error: boolean
                  code: number
                  message: string
                  data: 
                    properties: 
                      token: string
                      refresh: string
                example: !include examples/auth_login.json 
    /student-access/{code}:
      get:
        description: verifica si un studiante tiene acceso a gamma
        responses: 
          200:
            body: 
              application/json:
                properties: 
                  error: boolean
                  code: number
                  message: string
                  data: boolean
                examples:
                  access: !include examples/student_access_true.json
                  not_access: !include examples/student_access_false.json
